name: Run my porfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build -t pjgame841/porfolio .
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push
        run: docker push pjgame841/porfolio
      - name: Stop old images
        run: docker rm $(docker stop $(docker ps -a -q --filter ancestor=pjgame841/porfolio --format="{{.ID}}"))
      - name: Start
        run: docker run -p 80:80 pjgame841/porfolio