name: Run my porfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build -t pjgame841/porfolio .
      - name: Docker push
        run: docker push pjgame841/porfolio
      - name: Start
        run: docker run -p 80:80 pjgame841/porfolio