name: NextJS CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: NPM Install
        run: npm install
      - name: NextJS & Postcss build
        run: npm run build
        run: npm run build:css
      - name: Start
        run: npm start