name: Run my porfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build -t pjgame841/portfolio .
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push
        run: docker push pjgame841/portfolio
      - name: Stop old images
        run: docker rm $(docker stop $(docker ps -a -q --filter name=pj_portfolio --format="{{.ID}}"))
        continue-on-error: true
      - name: Start
        run: docker run -p 8080:8080 -d --name=pj_portfolio pjgame841/portfolio